# Generated by Django 5.0.6 on 2024-06-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
